"""需求编号到可执行用例的显式映射；保留源编号跳号和 P1 范围。"""

# ruff: noqa: E501

# 每行左侧为源需求，右侧为实际测试函数名；不根据模块整包通过推断逐项通过。
LINKS = """
CHN-F01 = test_concurrent_channel_code_and_first_member_rollback test_concurrent_channel_code_and_first_member_rollback test_environment_authorization_failure_rolls_back test_concurrent_environment_creation_keeps_one_entry test_staged_channel_environment_activates_authorization
IAM-F01 IAM-F13 IAM-A11 = test_concurrent_channel_code_and_first_member_rollback test_concurrent_normalized_login_names_accept_once test_concurrent_members_and_grants_accept_once_and_revision_conflicts
CHN-F02 CHN-A11 GLO-A22 = test_actual_schema_and_framework_storage test_scope_control_repository_and_cursor_boundaries test_authentication_missing_provider_fails_closed test_channel_context_is_cleared_and_message_is_only_locator
CHN-F03 CHN-F04 CHN-F05 CHN-A13 = test_two_real_channels_token_binding_masks_and_index test_identity_lookup_queries_always_scoped test_http_channel_key_creation_rotation_audit_and_invalid_references
CHN-A01 = test_two_real_channels_token_binding_masks_and_index test_identity_lookup_queries_always_scoped test_http_channel_key_creation_rotation_audit_and_invalid_references test_staged_channel_environment_activates_authorization
CHN-F06 CHN-A06 CHN-A16 = test_rotation_keeps_client_limits_overlap_and_revocation test_overlap_deadline_invalidates_old_token_without_redis_cleanup test_state_disable_rejects_existing_token_and_worker test_delegation_retry_keeps_one_run_across_api_key_rotation
CHN-F07 CHN-F13 CHN-A08 IAM-F08 IAM-A06 = test_cross_channel_reference_and_governance_does_not_grant_data test_governance_is_not_business_content_permission test_artifacts_isolate_channel_environment_domain_and_subject test_usage_delegates_explicit_authorized_scopes_and_records_platform_range
CHN-F08 CHN-A05 RUN-A11 RUN-F18 = test_worker_two_channels_same_agent_and_late_original_usage test_channel_context_is_cleared_and_message_is_only_locator test_foreign_channel_same_ids_are_untouched
CHN-F09 CHN-A03 IAM-F05 IAM-A01 IAM-A03 GLO-A01 GLO-A02 = test_mem_a03_a08_identical_subjects_do_not_cross_scopes_or_clear test_stable_pagination_title_and_channel_subject_isolation test_tol_a03_full_authorization_cache_isolation_and_revocation test_artifacts_isolate_channel_environment_domain_and_subject test_same_channel_environment_distinct_subjects_and_idempotency
CHN-F10 CHN-A07 = test_state_disable_rejects_existing_token_and_worker test_worker_two_channels_same_agent_and_late_original_usage test_archive_counts_actual_runs_and_allows_terminal_history test_archive_racing_admission_never_leaves_active_run_in_archived_channel
CHN-F11 CHN-F12 CHN-A09 USG-F12 USG-F13 USG-A10 GLO-A21 = test_channel_key_rotation_debug_evaluation_and_cross_scope_rejected test_actual_key_rotation_late_usage_remains_on_original_key test_all_admission_writes_rollback_with_later_limit_failure
CHN-F14 CHN-A12 = test_archived_channel_reclaims_shared_configuration_after_retention test_foreign_channel_same_ids_are_untouched test_restore_old_database_and_objects_replays_latest_manifest
CHN-F15 CHN-A14 = test_environment_concurrency_ownership_and_new_context test_state_disable_rejects_existing_token_and_worker
CHN-F16 CHN-A15 = test_environment_concurrency_ownership_and_new_context test_state_disable_rejects_existing_token_and_worker
CHN-F17 = test_client_permission_shrink_affects_existing_token test_rotation_keeps_client_limits_overlap_and_revocation
CHN-A02 IAM-F03 IAM-A02 INT-F02 INT-A02 GLO-A20 = test_no_context_override_or_direct_key_bearer test_untrusted_claims_are_rejected test_model_identity_override_is_blocked_before_business_dispatch
CHN-A04 RUN-F16 RUN-A01 = test_concurrent_first_admission_and_key_rotation test_delegation_retry_keeps_one_run_across_api_key_rotation test_checkpoint_dedup_recovery_and_stale_lease
CHN-A10 IAM-F09 IAM-A14 = test_switch_is_atomic_single_winner_and_preserves_old_run_scope test_workspace_atomic_switch_failure_and_session_indexes test_two_account_roles_multichannel_default_and_revocation
CHN-A17 = test_environment_hint_does_not_depend_on_service_or_key test_configuration_queries_are_constant_and_only_aggregate_current_page test_management_workspace_reports_environment_without_service_or_key test_configuration_status_does_not_expose_other_channels_or_environments
IAM-F02 IAM-A07 = test_concurrent_members_and_grants_accept_once_and_revision_conflicts test_membership_removal_is_channel_local_and_stops_worker test_scope_escalation_and_foreign_resources_are_rejected test_multichannel_validation_and_revision_conflict_roll_back_all_channels
IAM-F04 = test_http_delegation_and_anonymous_boundary test_sensitive_ephemeral_and_unverified_facts_rejected
IAM-F06 IAM-A04 = test_builder_can_edit_but_not_publish_self_grant_or_cross_scope test_agt_a01_tool_scopes_cannot_expand_caller_authorization
IAM-F07 IAM-A05 = test_reset_disable_and_logout_block_even_when_redis_cleanup_fails test_membership_removal_is_channel_local_and_stops_worker test_revoking_grant_stops_next_boundary_without_relying_on_menu
IAM-F10 = test_audit_records_real_changed_fields test_audit_filters_actual_changed_scope_and_records_denied_result
IAM-F11 IAM-A08 = test_token_ttl_deletion_and_expiry_cannot_be_renewed test_purposes_current_key_subject_caps_and_key_index
IAM-F12 IAM-A09 IAM-A13 GLO-A11 = test_iam_a09_a13_a14_direct_calls_and_same_member_records test_initial_password_and_creation_options_require_server_authority
IAM-F14 IAM-A12 INT-A09 = test_sse_auth_control_closes_but_task_survives test_file_bytes_are_not_delivered_after_token_revocation test_sync_window_input_contract_and_live_stream_revocation test_worker_requires_current_subject_and_never_widens_permissions
IAM-A10 GLO-A12 = test_redis_unavailable_is_503_and_errors_are_distinct test_token_ttl_deletion_and_expiry_cannot_be_renewed test_reset_disable_and_logout_block_even_when_redis_cleanup_fails
IAM-A15 = test_menu_tree_mutation_revision_protection_and_role_reference
IAM-A16 = test_platform_role_live_permissions_menu_visibility_and_no_account_takeover
IAM-A17 = test_specific_agent_catalog_grant_and_direct_access
IAM-A18 = test_more_than_two_hundred_rows_are_searchable_and_paginated
IAM-A19 = test_two_account_roles_multichannel_default_and_revocation test_pending_channel_assignment_never_creates_unscoped_access
IAM-A22 = test_platform_retains_admin_assignment_and_channel_hides_and_protects_it test_channel_created_roles_remain_assignable_without_new_action_restrictions
IAM-A21 = test_builtin_roles_and_account_choices_read_the_same_database test_custom_channel_role_assigns_multiple_channels_and_changes_live test_account_assignment_validates_role_scope_and_delegation
IAM-A20 = test_multichannel_validation_and_revision_conflict_roll_back_all_channels test_concurrent_channel_assignments_and_role_conversion test_channel_multiselect_does_not_leave_hidden_legacy_memberships
MOD-F01 MOD-F05 MOD-A02 = test_config_history_stale_capabilities_and_no_test_bypass test_model_validation_without_published_agent_creates_debug_run test_agt_a01_missing_dependencies_capabilities_and_channel_isolation
MOD-F02 = test_tenant_isolation_endpoint_policy_and_http_contract test_outbound_requires_scope_purpose_dns_and_safe_headers
MOD-F03 MOD-F09 = test_concurrent_model_alias_and_immutable_mapping test_configuration_history_isolated_by_environment test_multiple_attempts_currency_and_immutable_source
MOD-F04 = test_config_history_stale_capabilities_and_no_test_bypass
MOD-F06 MOD-A03 USG-F09 USG-A01 GLO-A04 = test_retry_preserves_attempts_and_unknown_usage test_model_concurrency_checks_actual_fallback_model test_multiple_attempts_currency_and_immutable_source test_concurrent_first_admission_and_key_rotation
MOD-F07 MOD-A04 = test_stream_failure_never_appends_fallback_text
MOD-F08 = test_revoked_connection_blocks_attempt_but_keeps_history test_model_use_grant_revocation_is_immediate
MOD-F10 AGT-F07 = test_schema_repair_is_finite_and_metered
MOD-A01 = test_same_client_two_configurations_sync_async_stream_and_cancel
MOD-A05 = test_restoring_endpoint_does_not_revive_old_evidence test_config_history_stale_capabilities_and_no_test_bypass
MOD-A06 USG-F02 = test_route_release_hard_price_gate_and_stale_revision test_no_price_token_budget_and_fixture_usage_missing_is_not_zero
USG-F01 USG-F04 USG-A03 GLO-A14 = test_concurrent_last_allowance_and_atomic_multi_policy_rollback test_channel_five_platform_twenty_and_fair_admission test_concurrent_first_admission_and_key_rotation
USG-F03 = test_growing_tool_context_rechecks_and_unpriced_is_not_zero
USG-F05 USG-A02 GLO-A08 = test_cumulative_dedup_final_precedence_and_late_correction test_no_price_token_budget_and_fixture_usage_missing_is_not_zero
USG-F06 = test_cumulative_dedup_final_precedence_and_late_correction test_budget_versions_alert_resolve_retrigger_and_repricing
USG-F07 USG-A04 = test_expired_sent_process_exit_and_idempotent_compensation test_model_return_then_crash_preserves_unknown_usage
USG-F08 USG-A05 = test_cancel_inflight_preserves_usage_without_success test_late_usage_keeps_numbers_and_discards_content
USG-F10 = test_budget_versions_alert_resolve_retrigger_and_repricing
USG-F11 USG-A07 = test_export_real_permissions_and_csv_formula_protection test_query_and_export_cannot_expand_scope_and_conversion_keeps_source
USG-A06 = test_multiple_attempts_currency_and_immutable_source test_query_and_export_cannot_expand_scope_and_conversion_keeps_source
USG-A08 = test_simultaneous_final_callback_and_next_reservation_preserve_exposure test_cumulative_dedup_final_precedence_and_late_correction
PRM-F01 PRM-F03 PRM-A05 = test_prm_a05_text_is_not_reparsed_and_platform_cannot_be_overridden test_untrusted_variable_cannot_be_promoted_to_system
PRM-F02 PRM-A01 = test_prm_a01_invalid_values_identify_chinese_field test_prm_a01_invalid_input_never_calls_runner test_http_variable_error_contains_chinese_path_without_raw_value
PRM-F04 = test_arbitrary_expressions_and_undeclared_variables_rejected test_repeated_large_binding_cannot_expand_without_bound
PRM-F05 = test_preview_masks_and_estimates_without_fake_remaining test_channel_and_environment_isolation_and_sensitive_permissions
PRM-F06 = test_prompt_sample_creates_metered_debug_run test_wrong_or_unbilled_evidence_cannot_publish
PRM-F07 = test_wrong_or_unbilled_evidence_cannot_publish test_missing_runner_and_evidence_fail_closed test_independent_publish_requires_explicit_resource_and_scope
PRM-F08 = test_compatibility_reports_required_type_length_source_output test_published_configuration_edit_keeps_old_snapshot
PRM-F09 PRM-F10 PRM-A04 PRM-A06 = test_published_configuration_edit_keeps_old_snapshot
PRM-F11 = test_portable_text_round_trip_keeps_sources_variables_and_delimiters test_prompt_http_permissions_export_and_channel_override
PRM-A02 = test_prm_a02_duplicate_create_and_revision_race
PRM-A03 = test_prm_a03_old_test_snapshot_and_result_stay_fixed
AGT-F01 = test_generic_workflows_and_legacy_entrypoints_are_separate test_legacy_definition_golden_files_and_importable_examples
AGT-F02 = test_missing_source_incompatible_output_and_required_input test_branch_must_be_exhaustive_and_source_must_dominate_consumer test_cycle_requires_registered_type_limits_and_exit
AGT-F03 AGT-A01 = test_agt_a01_missing_dependencies_capabilities_and_channel_isolation test_amount_budget_requires_prices_and_scope_overrides_fail test_prod_http_rechecks_evidence_and_draft_changes
AGT-F04 AGT-A04 = test_agt_a04_code_revision_and_mapping_races
AGT-F05 AGT-A02 GLO-A03 = test_actual_admission_keeps_queued_run_and_new_request_gets_new_version test_stateful_checkpoint_persists_and_lease_blocks_stale_writes
AGT-F06 = test_agt_a01_tool_scopes_cannot_expand_caller_authorization test_dependency_rebinding_unauthorized_tools_and_missing_capabilities
AGT-F08 AGT-A03 = test_tool_loop_stops_at_frozen_call_limit test_retry_counts_toward_model_limit test_step_timeout_drains_captured_usage
AGT-F09 = test_followup_creates_new_run_and_records_confirmed_conditions
AGT-F10 RUN-F14 = test_registered_compute_retry_and_schema_checked_partial test_partial_output_is_not_formal_result_and_missing_usage_not_zero
AGT-F11 = test_offline_and_emergency_preserve_history
AGT-F12 AGT-A05 = test_agt_a05_rollback_rechecks_disabled_tool
AGT-F13 = test_draft_dependency_revision_is_frozen_and_requires_publication test_candidate_draft_revision_and_no_runtime_field_override test_prod_http_rechecks_evidence_and_draft_changes
AGT-A06 = test_conversation_history_and_no_implicit_conversation test_stateless_calls_do_not_create_sessions_and_exports_reauthorize
SES-F01 = test_foreign_agent_and_attachment_are_rejected test_service_subject_isolation_and_management_scope_restore
SES-F02 = test_budget_rejection_rolls_back_message_and_occupancy test_run_entry_uses_message_id_before_http_key
SES-F03 SES-A01 = test_ses_a01_concurrent_different_messages_only_one_run
SES-F04 SES-A02 = test_ses_a02_replay_across_keys_and_release_changes
SES-F05 SES-A03 = test_ses_a03_partial_cancel_and_late_output test_sync_timeout_reuses_original_run_and_sse_replays
SES-F06 SES-F07 SES-A06 = test_ses_a06_versions_and_contract_change
SES-F08 = test_context_priorities_summary_sources_and_deletion_guard test_summary_generation_requires_metered_port_and_deletion_preview_sources
SES-F09 = test_stable_pagination_title_and_channel_subject_isolation test_management_rerun_creates_new_turn_and_replays
SES-F10 SES-F11 SES-A05 GLO-A05 = test_full_graph_removes_contents_and_preserves_independent_memory test_late_upload_cannot_recreate_deleted_object test_restore_old_database_and_objects_replays_latest_manifest test_deletion_drops_late_text_but_settles_usage
SES-F12 = test_stateless_calls_do_not_create_sessions_and_exports_reauthorize test_http_download_uses_live_session_and_attachment_headers
SES-A04 = test_ses_a04_archive_restore_and_terminal_compensation
MEM-F01 MEM-F10 MEM-A06 = test_mem_a06_disable_preserves_context_clear_preserves_switch test_unconfigured_agent_and_policy_reduction_disable_queued_reads test_reenable_does_not_revive_old_selection_or_old_automatic_write
MEM-F02 MEM-A01 = test_background_generates_layers_and_next_conversation_reads_confirmed_profile test_mem_a01_task_only_and_inference_never_become_fact test_queued_candidates_cannot_reintroduce_forgotten_or_cleared_content
MEM-F03 MEM-A02 = test_mem_a02_explicit_save_source_and_current_priority
MEM-F04 = test_concurrent_corrections_conflict_and_one_active_attribute
MEM-F05 MEM-A05 = test_mem_a05_deleted_source_is_unusable_before_cleanup test_expiration_and_replacement_invalidate_old_selection test_trusted_fact_value_matches_recorded_tool_result_and_requires_current_source
MEM-F06 MEM-A08 = test_mem_a03_a08_identical_subjects_do_not_cross_scopes_or_clear test_management_scope_restore_and_cursor_binding
MEM-F07 = test_sensitive_ephemeral_and_unverified_facts_rejected
MEM-F08 MEM-A04 = test_mem_a04_forget_blocks_queued_refs_and_history_and_tracks_cleanup test_memory_clear_finishes_legacy_job_and_old_worker_is_blocked
MEM-F09 = test_independent_source_survives_without_deleted_source_or_history_content test_actual_conversation_deletion_preserves_independent_memory
MEM-F12 = test_background_generates_layers_and_next_conversation_reads_confirmed_profile
MEM-F13 = test_removing_one_message_revokes_whole_archive_and_unconfirmed_profile
MEM-F14 = test_failed_background_run_retries_with_same_batch_and_no_duplicate_memories test_pending_generation_rechecks_clear_source_and_permission test_late_model_result_cannot_write_after_memory_disabled
MEM-F15 = test_channel_attributes_are_configured_and_not_a_platform_business_catalog test_baseline_upgrade_preserves_memory_and_explicit_or_implicit_policy
MEM-F11 = test_degrade_records_warning_and_auth_errors_never_degrade test_memory_omission_is_reported_in_business_result
MCP-F01 MCP-F04 MCP-A01 = test_discovery_does_not_grant_and_atomic_repeat_import test_health_schedule_claim_threshold_and_manual_status_are_independent
MCP-F02 MCP-F08 MCP-A03 MCP-A04 = test_cross_scope_same_name_credential_rotation_and_revocation test_paginated_handshake_and_isolated_authentication
MCP-F03 = test_safe_protocol_failures test_outbound_requires_scope_purpose_dns_and_safe_headers
MCP-F05 = test_execution_uses_only_bound_credential_and_injects_server_identity test_discovery_does_not_grant_and_atomic_repeat_import
MCP-F06 MCP-F07 MCP-A02 INT-F08 = test_remote_drift_blocks_old_binding_and_imports_new_target_version test_connection_revision_never_upgrades_published_binding
MCP-F09 = test_changed_contract_prevents_call_and_disconnect_never_replays
MCP-F10 = test_unified_executor_records_attempt_and_preserves_inflight_result test_platform_revocation_blocks_later_mcp_calls
MCP-F11 MCP-A06 = test_mcp_structured_file_reference_is_rejected_by_tool_layer test_adapter_and_tool_result_validation test_result_freshness_pagination_size_and_file_reference
TOL-F01 = test_create_race_freeze_release_and_disabled_metadata test_contract_limits
TOL-F02 TOL-A01 = test_tol_a01_trusted_fields_never_reach_source test_model_identity_override_is_blocked_before_business_dispatch
TOL-F03 = test_current_subject_refusal_prevents_business_call test_platform_revocation_blocks_later_mcp_calls
TOL-F04 = test_management_api_schema_errors_and_no_arbitrary_execution_route test_tool_loop_stops_at_frozen_call_limit
TOL-F05 TOL-A02 GLO-A06 = test_tol_a02_invalid_price_and_evidence_do_not_become_facts test_result_freshness_pagination_size_and_file_reference
TOL-F06 = test_recoverable_retry_has_independent_attempt_and_evidence test_retry_does_not_bypass_runtime_limit
TOL-F08 TOL-A03 = test_tol_a03_full_authorization_cache_isolation_and_revocation test_cached_deleted_evidence_cannot_be_returned
TOL-F09 TOL-A04 = test_tol_a04_agent_whitelist_rejection_is_locatable test_registry_never_resolves_another_channel
TOL-F10 = test_real_call_attempt_evidence_cache_and_fixed_dependency test_published_agent_uses_mcp_through_shared_worker_pipeline
TOL-F11 = test_create_race_freeze_release_and_disabled_metadata test_missing_runtime_and_disable_during_call_fail_closed
TOL-A05 = test_tol_a05_real_effect_is_not_inferred_from_transport
SKL-F01 = test_metadata_portability_and_actual_hash test_create_freeze_fork_load_and_release_preserve_history
SKL-F02 SKL-A01 = test_invalid_packages_are_rejected test_links_and_duplicate_entries_rejected test_concurrent_codes_edits_and_invalid_import_leave_no_manifest
SKL-F03 SKL-F08 SKL-A06 = test_budget_omission_and_unsupported_scripts_are_explicit test_sensitive_export_is_refused_and_scripts_are_inert
SKL-F04 SKL-A02 = test_discovery_does_not_read_any_files_and_selected_only_loads_requested test_skill_loading_without_agent_records_files_in_debug
SKL-F05 SKL-F06 SKL-A03 = test_dependency_rebinding_unauthorized_tools_and_missing_capabilities test_unauthorized_tools_and_conflicting_skills_never_produce_context
SKL-F07 = test_priority_variables_and_current_state test_unauthorized_tools_and_conflicting_skills_never_produce_context
SKL-F09 SKL-A04 = test_create_freeze_fork_load_and_release_preserve_history test_text_configuration_debug_evaluation_publish_and_new_candidate
SKL-F10 SKL-A05 = test_import_validation_export_scope_and_cross_channel test_sensitive_export_is_refused_and_scripts_are_inert
SKL-F11 = test_priority_variables_and_current_state test_file_deleted_after_read_is_not_returned_to_runtime
RUN-F01 = test_session_budget_and_message_atomicity test_candidate_draft_revision_and_no_runtime_field_override
RUN-F02 RUN-A02 = test_admission_commit_without_publish_and_queue_failure
RUN-F03 RUN-A03 = test_published_unconfirmed_and_dual_workers test_real_celery_duplicate_messages_are_only_wakeups test_channel_context_is_cleared_and_message_is_only_locator
RUN-F04 = test_real_fifteen_second_sync_window_retains_run test_sync_timeout_reuses_original_run_and_sse_replays
RUN-F05 RUN-F06 RUN-A04 = test_same_client_two_configurations_sync_async_stream_and_cancel test_sync_window_input_contract_and_live_stream_revocation test_conversation_artifact_expired_events_and_scope_rejection test_real_fifteen_second_sync_window_retains_run
RUN-F07 = test_queued_deadline_rerun_and_output_validation test_step_timeout_drains_captured_usage
RUN-F08 = test_finite_retries_and_event_sequence_under_concurrency test_retry_counts_toward_model_limit
RUN-F09 RUN-A07 = test_recovery_cannot_restart_blocked_run test_deleted_checkpoint_cannot_be_recreated test_cross_channel_message_cannot_execute
RUN-F10 RUN-A05 = test_concurrent_success_and_cancel_never_reverse_terminal test_cancel_inflight_preserves_usage_without_success
RUN-F11 RUN-F12 RUN-A06 = test_process_exit_after_remote_return_keeps_attempt_and_pending_cost test_unknown_sent_response_never_resends test_stateful_crash_recovers_saved_response_and_fences_old_lease
RUN-F13 RUN-A08 = test_queued_deadline_rerun_and_output_validation test_management_rerun_creates_new_turn_and_replays test_queued_deadline_uses_configured_sixty_or_three_hundred
RUN-F15 = test_deletion_drops_late_text_but_settles_usage test_deleted_checkpoint_cannot_be_recreated test_restore_old_database_and_objects_replays_latest_manifest
RUN-A09 = test_concurrent_first_admission_and_key_rotation test_checkpoint_dedup_recovery_and_stale_lease test_concurrent_success_and_cancel_never_reverse_terminal
EVL-F01 = test_import_csv_mapping_unicode_newlines_and_bad_row test_import_atomicity_and_label_versioning
EVL-F02 EVL-A06 = test_reviewed_run_source_redacts_and_propagates_subject_deletion test_equivalent_independent_source_survives_deletion_and_report_changes
EVL-F03 EVL-A01 = test_same_data_baseline_comparison test_complete_report
EVL-F04 EVL-F05 = test_fixture_uses_fixed_result_and_rechecks_current_permission test_forbid_schema_network_reference_and_empty_assertions
EVL-F06 EVL-A05 = test_deterministic_failure_wins_over_semantic_score test_missing_values_cannot_equal_null_and_citations_need_authorized_evidence
EVL-F07 = test_human_disagreement_is_independent_and_blocks_release
EVL-F08 EVL-A04 = test_cancel_counts_unexecuted_and_preserves_usage test_pause_duplicate_dispatch_and_single_rerun test_worker_sweep_reserves_budget_and_keeps_full_denominator
EVL-F09 EVL-A02 = test_release_content_change_and_initial_baseline test_prod_http_rechecks_evidence_and_draft_changes
EVL-F10 EVL-A03 GLO-A10 = test_critical_failure_blocks_even_at_zero_quality_threshold test_two_shapes_full_case_matrix test_release_content_change_and_initial_baseline
EVL-F11 = test_import_atomicity_and_label_versioning test_reviewed_run_source_redacts_and_propagates_subject_deletion
INT-F01 = test_configured_reader_and_two_business_schemas test_cross_scope_same_name_credential_rotation_and_revocation
INT-F03 INT-A03 = test_arbitrary_channel_issues_credentials_without_business_category test_http_delegation_and_anonymous_boundary
INT-F04 = test_result_status_scope_effect_and_entity_authorization
INT-F05 = test_current_subject_refusal_prevents_business_call test_current_review_revoking_execution_cannot_be_reexpanded_by_identity
INT-F06 = test_configured_reader_and_two_business_schemas
INT-F07 = test_result_freshness_pagination_size_and_file_reference
INT-F09 INT-A05 GLO-A07 = test_result_status_scope_effect_and_entity_authorization test_timeout_missing_configuration_and_delegation_revocation test_missing_values_cannot_equal_null_and_citations_need_authorized_evidence
INT-F10 = test_same_client_two_configurations_sync_async_stream_and_cancel test_published_agent_uses_mcp_through_shared_worker_pipeline
INT-F11 INT-A07 GLO-A09 = test_current_build_three_channels_complete_management_flow
INT-F12 INT-A08 = test_no_context_override_or_direct_key_bearer test_reauthentication_key_rotation_and_current_revocation
INT-F13 = test_subject_binding_updates_are_serialized_and_scope_is_server_owned test_environment_concurrency_ownership_and_new_context
INT-F14 INT-A06 = test_schema_changes_and_missing_dictionary_names_fail_closed test_unimplemented_capability_never_falls_back
INT-A01 = test_same_client_two_configurations_sync_async_stream_and_cancel test_sync_window_input_contract_and_live_stream_revocation
INT-A04 = test_adapter_and_tool_result_validation test_followup_creates_new_run_and_records_confirmed_conditions
"""

PLANS = {
    "GLO": "03、11、17、23–26",
    "CHN": "05、06、19",
    "IAM": "04、06、18",
    "MOD": "07、17",
    "USG": "08",
    "PRM": "09",
    "AGT": "16、17、21",
    "SES": "12",
    "MEM": "13、25",
    "MCP": "14、20",
    "TOL": "10、20",
    "SKL": "15、21",
    "RUN": "11、17、22",
    "EVL": "24、25",
    "INT": "18–23",
}
DEFERRED = {
    "MEM-A03": "语义向量检索为 P1；同号主体的 P0 属性隔离见 MEM-A08。",
    "MCP-A05": "业务写操作为 P1；P0 只读断线不重放见 MCP-F09。",
    "TOL-F07": "业务写入结果核查为 P1；P0 模型未知响应恢复见 RUN-A06。",
    "TOL-A06": "源业务写工具及写入状态查询为 P1。",
}
PARTIAL = {
    "CHN-A17": "集成用例覆盖状态、关联有效性、分页和授权隔离；红绿呈现、窄屏及快捷跳转另执行前端 tests/channels.spec.ts，不从后端通过推断页面验收。",
    "CHN-A03": "仅验收属性、会话和缓存；向量检索后续阶段。",
    "MEM-A08": "仅验收属性、清空和工作区隔离；向量召回后续阶段。",
    "MEM-F06": "仅验收属性检索；向量检索后续阶段。",
    "MEM-F08": "仅验收已实现的内容和缓存；向量索引后续阶段。",
    "MCP-F02": "本次验收服务凭据；OAuth 用户委托后续阶段。",
    "RUN-F12": "本次验收模型/只读步骤的未知结果；业务写工具后续阶段。",
    "TOL-F06": "本次验收只读重试；业务写入幂等后续阶段。",
    "EVL-F04": "固定数据与实时只读权限边界已关联；真实供应商与 MCP 的评测组合待验。",
    "EVL-F06": "确定性断言已关联；本轮没有调用真实语义裁判。",
    "EVL-A05": "验证确定性失败优先的判定规则；语义分由夹具提供。",
    "MOD-A01": "缺少两种真实模型组合及同一 Agent 的实测用量；受控用例不满足本项。",
    "MOD-F01": "已关联配置/调试回归；真实供应商鉴权与能力待验。",
    "MOD-F04": "已关联参数白名单回归；具体供应商接受的参数仍须实测。",
}
